### ISSUE TITLE
bosh-257 breaks spec.networks

### ISSUE THREAD

**Issue by JamesClonk** [cloudfoundry/bosh#1318]
bosh 257 seems to break this spec `<%= spec.networks.send(spec.networks.methods(false).first).ip %>` for trying to figure out the IP in boshreleases. We're not using cloud-config yet, it also prints out a warning before it fails during deployment preparation / filling out the erb templates: Deprecation: Ignoring cloud config. Manifest contains 'networks' section.                     

I already had 3 different boshreleases fail deployment because of this.
```
Started preparing deployment > Preparing deployment. Done (00:00:00)

Error 100: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'authproxy_z1'. Errors are:
     - Unable to render templates for job 'authproxy'. Errors are:
       - Error filling in template 'registrar_settings.yml.erb' (line 9: nil is not a symbol nor a string)
       - Error filling in template 'properties.sh.erb' (line 16: nil is not a symbol nor a string)
```
line 9 and line 16 are the `spec.networks.send(spec.networks.methods(false).first).ip` lines..          

It also seems to break a simpler `<%= spec.networks.redisnet1.ip %>`:
```
Started preparing deployment > Preparing deployment. Done (00:00:00)

Error 100: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'redis-ha_z1'. Errors are:
     - Unable to render templates for job 'redis'. Errors are:
       - Error filling in template 'redis.conf.erb' (line 61: undefined method `ip' for nil:NilClass)
     - Unable to render templates for job 'redis-sentinel'. Errors are:
       - Error filling in template 'redis-sentinel_ctl.erb' (line 35: undefined method `ip' for nil:NilClass)
       - Error filling in template 'post-start.erb' (line 45: undefined method `ip' for nil:NilClass)
```

It looks like `spec.networks.*` is not returning anything.

**Comment by JamesClonk** [comment]
it worked in bosh 256.10 still, so this problem was introduced with bosh 257.

**Comment by cppforlife** [comment]
@JamesClonk hmm. looks like one of the ruby 2.3 upgrade fixes did not get merged. we are merging this in and are planning to release 257.1 version (https://www.pivotaltracker.com/story/show/122561571).

**Comment by cppforlife** [comment]
Fixed in v257.1.
