### ISSUE TITLE
health_monitor crashes instead of raising error if authentication fails.

### ISSUE THREAD

**Issue by jimconner** [cloudfoundry/bosh#2291]
**Describe the bug**
health_monitor fails to emit the correct error messages if client_id and client_secret are not set correctly and instead complains `undefined method 'uri'  for #<EventMachine::HttpClient:0x000055a5a6edd540>`

We discovered this during an upgrade from bosh 270.10.0 - We are using bosh-deployment for our bosh manifest and had failed to notice the changes in uaa.yml which are injecting the client_id and client_secret values for health monitor to use.  This meant that our health_monitor config contained only the old user/pass fields but had client_id and client_secret as empty strings.

When health_monitor attempts to start up it will fetch /configs and /deployments from port 25555. If the code gets a non-200 status code back it will then attempt to raise an error. The line raising the error is trying to print out #{http.uri} and this is causing a fatal error because 'uri' is not an undefined method. This causes health_monitor to crash.

Supplying the correct details for client_id and client_secret means that the error raising code is never called and is the effective workaround to this problem. 

Printing of the correct error message was working correctly on bosh 270.10.0

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director v271.2.0 on vmware with default config
2. I was using stemcell 621.92 when I discovered the problem, but I don't think it's stemcell specific.
3. Set the client_id and client_secret fields in /var/vcap/jobs/health_monitor/config/health_monitor.yml to be empty strings.
4. Monit restart health_monitor
5. Health montior will crash at startup. It will not print the correct error message about '401 not authorised' because it hits the 'uri undefined method' when trying to print out the URL that has been called.

**Expected behavior**
health_monitor prints out the correct error message 'Could not get resurrection config from director at <some_url>'

**Logs**
```sh
F, [2020-11-23T17:47:27.393844 #9191] FATAL : undefined method `uri' for #<EventMachine::HttpClient:0x000055a5a6edd540>
F, [2020-11-23T17:47:27.393926 #9191] FATAL : /var/vcap/data/packages/health_monitor/068aa86a68c8b1bf4d23ac40f2089d09d505a432/gem_home/ruby/2.6.0/gems/bosh-monitor-0.0.0/lib/bosh/monitor/director.rb:14:in `deployments'
/var/vcap/data/packages/health_monitor/068aa86a68c8b1bf4d23ac40f2089d09d505a432/gem_home/ruby/2.6.0/gems/bosh-monitor-0.0.0/lib/bosh/monitor/runner.rb:161:in `fetch_deployments'
/var/vcap/data/packages/health_monitor/068aa86a68c8b1bf4d23ac40f2089d09d505a432/gem_home/ruby/2.6.0/gems/bosh-monitor-0.0.0/lib/bosh/monitor/runner.rb:121:in `block in poll_director'
I, [2020-11-23T17:47:27.393963 #9191]  INFO : HealthMonitor shutting down...
I, [2020-11-23T17:47:27.394076 #9191]  INFO : HealthMonitor exiting!
```

**Versions (please complete the following information):**
 - Infrastructure: vSphere 6.7
 - BOSH version: 271.2.0
 - BOSH CLI version: n/a
 - Stemcell version: 621.92 (Ubuntu)

**Additional context**
Error is only hit when health_monitor is not correctly configured with client_id and client_secret. This should cause the director.rb to raise an error, but raising of that error is failing because it is trying to use an undefined method when printing out the error message. This causes health_monitor to crash.

**Comment by theozaurus** [comment]
I've also run into this issue

**Comment by theozaurus** [comment]
Switching it to `[last_effective_url](https://www.rubydoc.info/gems/em-http-request/1.1.3/EventMachine%2FHttpClient:last_effective_url)` seems to work.
